#!/usr/bin/env python
# coding=utf-8
"""
@author     phenixyang
@date       2012-11-2
@brief      const define
@modify     2012-12-25 add TYPE_INNERHEADER
"""

#const variant
SESSION_LEN = 28

#service id
SID_SESSION = 0
SID_HEART_BEAT = 1
SID_UPDATE = 2
SID_CONFIG = 3
SID_DATA_REPORT = 4
SID_URL_QUERY = 11
SID_CLOUD_QUERY = 10
SID_UPLOAD_QUERY = 20
SID_SOFT_MANAGER = 101

#buffer type
TYPE_HEADER = 0
TYPE_BODY = 1
TYPE_UPLOAD = 2
TYPE_TRANSFER = 3
TYPE_INNERHEADER = 4

#inner cmd id
IN_CMD_INNER_CLOUD_QUERY = 100
IN_CMD_NOTICEDISPATCHER = 130
IN_CMD_NOTICEDC = 131
IN_CMD_FILE_PROCESSOR = 132
IN_CMD_DISPATCHTASK = 170
IN_CMD_SCANRESULT = 171   # Datacenter forward
IN_CMD_WHITE_REPORT = 173 # Datacenter forward
IN_CMD_HAND_REPORT = 174  # Datacenter forward
IN_CMD_SENDBASICINFO = 190
IN_CMD_SENDPATHINFO = 191
IN_CMD_SENDPEINFO = 192
#IN_CMD_SENDDCINFO = 193   # useless
IN_CMD_SENDOFFLINEDISPATCHERINFO = 194
IN_CMD_WEB = 195
IN_CMD_SENDVDCINFO = 175
IN_CMD_SENDHOTWIDEINFO = 176
IN_CMD_PESUMMARYINFO = 177      #pe summary add
IN_CMD_COLLECTOR_ENGINE_RESULT = 178
IN_CMD_SENDURLINFO = 196
IN_CMD_DEFENCE = 197
IN_CMD_DEFENCE_RES = 198

#inner sub cmd
IN_SUBCMD_IN = 1
IN_SUBCMD_OUT = 2

#url level define
LEVEL_LINK = 1
LEVEL_SITE = 2
LEVEL_DOMAIN = 3

#md5 type
MD5_TYPE_ALL = 0
MD5_TYPE_PART = 1

#file type
FILE_TYPE_PE = 0
FILE_TYPE_NOPE = 1
