# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vdc_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vdc_message.proto',
  package='',
  serialized_pb='\n\x11vdc_message.proto\"\x9b\x01\n\x0bInnerHeader\x12\x0b\n\x03\x63md\x18\x01 \x02(\r\x12\x0e\n\x06subcmd\x18\x02 \x02(\r\x12\x0b\n\x03seq\x18\x03 \x02(\r\x12\x14\n\x0cprotoversion\x18\x04 \x02(\r\x12\x13\n\x08src_addr\x18\x05 \x01(\r:\x01\x30\x12\x13\n\x08src_port\x18\x06 \x01(\r:\x01\x30\x12\x11\n\x06socket\x18\x07 \x01(\r:\x01\x30\x12\x0f\n\x07\x63ontext\x18\t \x03(\x0c\"!\n\rSampleTaskReq\x12\x10\n\x08\x66ile_cnt\x18\x01 \x02(\r\"0\n\rSampleTaskRep\x12\x12\n\nresult_cnt\x18\x01 \x02(\r\x12\x0b\n\x03md5\x18\x02 \x03(\x0c\"<\n\nResultInfo\x12\x0b\n\x03md5\x18\x01 \x02(\x0c\x12\r\n\x05level\x18\x02 \x02(\r\x12\x12\n\nvirus_name\x18\x03 \x01(\x0c\"D\n\rResultTaskReq\x12\x11\n\treply_cnt\x18\x01 \x02(\r\x12 \n\x0bresult_info\x18\x02 \x03(\x0b\x32\x0b.ResultInfo\"0\n\rResultTaskRep\x12\x12\n\nresult_cnt\x18\x01 \x02(\r\x12\x0b\n\x03md5\x18\x02 \x03(\x0c')




_INNERHEADER = _descriptor.Descriptor(
  name='InnerHeader',
  full_name='InnerHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='InnerHeader.cmd', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subcmd', full_name='InnerHeader.subcmd', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='InnerHeader.seq', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protoversion', full_name='InnerHeader.protoversion', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_addr', full_name='InnerHeader.src_addr', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='InnerHeader.src_port', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='socket', full_name='InnerHeader.socket', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='InnerHeader.context', index=7,
      number=9, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=177,
)


_SAMPLETASKREQ = _descriptor.Descriptor(
  name='SampleTaskReq',
  full_name='SampleTaskReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_cnt', full_name='SampleTaskReq.file_cnt', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=179,
  serialized_end=212,
)


_SAMPLETASKREP = _descriptor.Descriptor(
  name='SampleTaskRep',
  full_name='SampleTaskRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_cnt', full_name='SampleTaskRep.result_cnt', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='md5', full_name='SampleTaskRep.md5', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=214,
  serialized_end=262,
)


_RESULTINFO = _descriptor.Descriptor(
  name='ResultInfo',
  full_name='ResultInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='md5', full_name='ResultInfo.md5', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='ResultInfo.level', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='virus_name', full_name='ResultInfo.virus_name', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=264,
  serialized_end=324,
)


_RESULTTASKREQ = _descriptor.Descriptor(
  name='ResultTaskReq',
  full_name='ResultTaskReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_cnt', full_name='ResultTaskReq.reply_cnt', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_info', full_name='ResultTaskReq.result_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=326,
  serialized_end=394,
)


_RESULTTASKREP = _descriptor.Descriptor(
  name='ResultTaskRep',
  full_name='ResultTaskRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_cnt', full_name='ResultTaskRep.result_cnt', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='md5', full_name='ResultTaskRep.md5', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=396,
  serialized_end=444,
)

_RESULTTASKREQ.fields_by_name['result_info'].message_type = _RESULTINFO
DESCRIPTOR.message_types_by_name['InnerHeader'] = _INNERHEADER
DESCRIPTOR.message_types_by_name['SampleTaskReq'] = _SAMPLETASKREQ
DESCRIPTOR.message_types_by_name['SampleTaskRep'] = _SAMPLETASKREP
DESCRIPTOR.message_types_by_name['ResultInfo'] = _RESULTINFO
DESCRIPTOR.message_types_by_name['ResultTaskReq'] = _RESULTTASKREQ
DESCRIPTOR.message_types_by_name['ResultTaskRep'] = _RESULTTASKREP

class InnerHeader(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INNERHEADER

  # @@protoc_insertion_point(class_scope:InnerHeader)

class SampleTaskReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLETASKREQ

  # @@protoc_insertion_point(class_scope:SampleTaskReq)

class SampleTaskRep(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLETASKREP

  # @@protoc_insertion_point(class_scope:SampleTaskRep)

class ResultInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULTINFO

  # @@protoc_insertion_point(class_scope:ResultInfo)

class ResultTaskReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULTTASKREQ

  # @@protoc_insertion_point(class_scope:ResultTaskReq)

class ResultTaskRep(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULTTASKREP

  # @@protoc_insertion_point(class_scope:ResultTaskRep)


# @@protoc_insertion_point(module_scope)
